### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oifj34f34f** [yevhen2ii/itunesify#1]
First of all, thank you for your promising project :)
When I run:

```
python itunesify.py -d /home/user/Music/
```

there is an endless connection. I think it's because I live in Russia. How can I debug this? Help me please

**Comment by yevhen2ii** [comment]
Hi, thanks for trying out iTunesify and providing your feedback! I'm sorry to hear you're experiencing an issue with an endless connection.

In order to help you debug the problem, please follow these steps:

1. **Test your connection to the iTunes API**: Open your web browser and try accessing the following URL: [https://itunes.apple.com/search?term=artist+album&media=music&entity=album&attribute=albumTerm&country=US](https://itunes.apple.com/search?term=artist+album&media=music&entity=album&attribute=albumTerm&country=US)

Replace "artist" and "album" with an actual artist and album name, respectively. If the page loads and returns a JSON response, it means you can access the iTunes API, and the issue might be related to the itunespy library or your script execution.

2. **Test itunespy functionality**: You can create a simple Python script to test whether itunespy is able to connect to the iTunes API and fetch data. For example:

```python
import itunespy

def main():
    artist_name = 'Coldplay'
    album_name = 'Parachutes'

    search_term = f'{artist_name} {album_name}'
    albums = itunespy.search_album(search_term)
    
    for album in albums:
        print(album.artist_name, album.collection_name)

if __name__ == '__main__':
    main()
```

3. **Consider using a VPN**: If you are unable to access the iTunes API or experience endless connection issues, it could be due to regional restrictions. In this case, consider using a VPN to connect to a server in the United States or another country where the iTunes API is accessible. This might resolve the connection issue.

Please let me know if any of these steps help resolve your issue, or if you have any further questions.

**Comment by oifj34f34f** [comment]
Thank you for the detailed explanation! I actually discovered the problem during the first step - neither my browser nor the script is loading the link. I will continue investigating why this is happening. Thanks again!
